export const DEMO_AUCTIONS = [
  {
    id: "66c8f4dd937750734d101001",
    product: {
      name: "Leica M6 Classic",
      description: "A carefully kept 35mm rangefinder with original body cap and strap.",
      category: "cameras",
      condition: "LIKE_NEW",
      images: [],
    },
    sellerId: "seller-one",
    startingPrice: 115000,
    currentBid: 142500,
    minimumIncrement: 2500,
    status: "LIVE",
    endTime: new Date(Date.now() + 1000 * 60 * 43).toISOString(),
    bidCount: 18,
    color: "coral",
  },
  {
    id: "66c8f4dd937750734d101002",
    product: {
      name: "Grand Seiko SBGA211",
      description: "The Snowflake dial, Spring Drive movement, and full titanium bracelet.",
      category: "watches",
      condition: "USED",
      images: [],
    },
    sellerId: "seller-two",
    startingPrice: 280000,
    currentBid: 316000,
    minimumIncrement: 5000,
    status: "LIVE",
    endTime: new Date(Date.now() + 1000 * 60 * 81).toISOString(),
    bidCount: 27,
    color: "blue",
  },
  {
    id: "66c8f4dd937750734d101003",
    product: {
      name: "Eames Lounge Chair",
      description: "Walnut shell with black leather, restored and authenticated.",
      category: "design",
      condition: "REFURBISHED",
      images: [],
    },
    sellerId: "seller-three",
    startingPrice: 175000,
    currentBid: 0,
    minimumIncrement: 5000,
    status: "SCHEDULED",
    startTime: new Date(Date.now() + 1000 * 60 * 180).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 520).toISOString(),
    bidCount: 0,
    color: "sage",
  },
  {
    id: "66c8f4dd937750734d101004",
    product: {
      name: "Macintosh 128K",
      description: "Early production example with keyboard, mouse, and carrying case.",
      category: "collectibles",
      condition: "USED",
      images: [],
    },
    sellerId: "seller-four",
    startingPrice: 95000,
    currentBid: 123000,
    minimumIncrement: 3000,
    status: "LIVE",
    endTime: new Date(Date.now() + 1000 * 60 * 136).toISOString(),
    bidCount: 11,
    color: "amber",
  },
];

export const DEMO_BIDS = [
  { id: "bid-1", auctionId: DEMO_AUCTIONS[0].id, amount: 142500, status: "ACCEPTED", createdAt: new Date().toISOString() },
  { id: "bid-2", auctionId: DEMO_AUCTIONS[1].id, amount: 305000, status: "ACCEPTED", createdAt: new Date(Date.now() - 3600000).toISOString() },
];
